sonar.projectKey=DevOps-SRE-Project
sonar.projectName=DevOps-SRE-Project
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=tests
sonar.python.version=3.11

sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/*test*.py,**/static/**,**/__pycache__/**

sonar.sourceEncoding=UTF-8
